### ISSUE TITLE
Spread pods across nodes

### ISSUE THREAD

**Issue by Qwerios** [nats-io/nats-streaming-operator#15]
I noticed after running the operator that sometimes the streaming pods would end up on the same node. I prefer spreading pods across multiple nodes in case of a rare node failure.

This is the yaml I usually add to either my deployment or pod yamls:

```yaml
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nats-streaming
        topologyKey: kubernetes.io/hostname
```

Is this something that could be of use for the operator?

**Comment by wallyqs** [comment]
Added a `template` parameter to the pod spec, so now possible to set anti affinity policy for example:

```yaml
---
apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "example-stan-anti"
spec:
  size: 3
  natsSvc: "example-nats"

  # Define Custom Pod Spec
  template:
    spec:
      volumes:
      - name: stan-secret
        secret:
          secretName: stan-secret
      containers:
        - name: nats-streaming
          volumeMounts:
          - mountPath: /etc/stan/config
            name: stan-secret
            readOnly: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: stan_cluster
                    operator: In
                    values:
                    - example-stan-anti
              topologyKey: kubernetes.io/hostname
```
