### ISSUE TITLE
Restrict RBAC access

### ISSUE THREAD

**Issue by metalmatze** [nats-io/nats-streaming-operator#17]
I don't think this operator needs all verbs on these Kubernetes objects. We should make sure to have less access.

```
# Allow actions on basic Kubernetes objects
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs: ["*"]
```
