### ISSUE TITLE
Enable monitoring

### ISSUE THREAD

**Issue by taddgiles** [nats-io/nats-streaming-operator#31]
Is there a way to enable http monitoring with the nats-streaming-operator?

`/streaming/serverz` and such.

I tried adding a container args to the k8s config.

```
---
apiVersion: streaming.nats.io/v1alpha1
kind: NatsStreamingCluster
metadata:
  name: nats-streaming-cluster
spec:
  size: 3
  natsSvc: nats-cluster
  template:
    spec:
      containers:
        - args: ["--http_port=8222", "--stan_debug=true", "--stan_trace=true"]
``` 

But the default operator config doesn't create a service that would work for that.
