### ISSUE TITLE
Can't install `natscluster` and `natsstreamingcluster` into namespace

### ISSUE THREAD

**Issue by exu** [nats-io/nats-streaming-operator#33]
nats.yaml 
```
---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
  namespace: "nats"
spec:
  size: 3
```

nats-straming.yaml 
```
---
apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "nats-streaming-cluster"
  namespace: "nats"
spec:
  size: 3
  natsSvc: "nats-cluster"
```

After `kubectl apply` there is no pods spawned in given namespace. Is there any workaround for this?
